#!/bin/bash
# Loop through each line in file.
file=$1

while read line  
do
	# Loop through each value in line.
	for elem in ${line[@]}
	do
		echo "$elem"
	done
	echo ""
	 

done < $file 			# $1 is the first command line arg.
