#!/bin/bash
#

err="Usage: stats {-rows|-cols} [file]"

# Validate command line arguments.
if [ $# -lt 2 ]					# No command line arguments were passed.
then
	echo "$err"
	exit 1
elif [ $# -gt 2 ]				# More than two command line arguments were passed.
then
	echo "$err"
	exit 1
fi

# Arguments valid so lets declare variables.
sort=$1
file=$2
row_sum=0
elem_count=0
avg=0
round_up=0.5
rounded_avg=0
numerator=0
echo "$sort"

# Loop through each line in file. ROWS
while read line
do
	# Loop through each value in line.
	for elem in ${line[@]}
	do
		echo "$elem" >> tmp
		row_sum=`expr $row_sum + $elem`
		elem_count=`expr $elem_count + 1`
	done
	echo "Row sum: $row_sum"
	echo "Elem count: $elem_count"

	# Calculate median
	sorted_line=($(cat tmp | sort))
	middle=$(($elem_count/2))
	if [ $(($elem_count%2)) -eq 0 ]
	then
		m1=${sorted_line[$middle]}
		m2=${sorted_line[$(($middle-1))]}
		median=$(((m1+m2)/2))
	else
		median=${sorted_line[$middle]}
	fi
	echo "median: $median"
	
	# Calculate average
	numerator=$(($row_sum*10))
	denominator=$elem_count
	avg=$(((($numerator/$denominator)+5)/10))
	echo "Avg: $avg"
	row_sum=0
	elem_count=0
	echo ""

	rm tmp

done < "$file" 			# $1 is the first command line arg.

# Loop through each column in file.

columns="$(head -1 test_file | wc -w)"
echo "$columns"
while read column
do
	echo $column

done < "$file"
